import type {
  Product,
  Order,
  ExporterProfile,
  ClientProfile,
  Review,
  Category,
  Notification,
  AnalyticsOverview,
  RevenueDataPoint,
  TopProduct,
  LogisticsShipment,
  OrderStatus,
  PaymentStatus,
  UserRole,
} from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Agricultura",
    slug: "agricultura",
    icon: "🌾",
    productCount: 234,
  },
  {
    id: "cat-2",
    name: "Alimentos y Bebidas",
    slug: "alimentos-bebidas",
    icon: "🍫",
    productCount: 187,
  },
  {
    id: "cat-3",
    name: "Textiles",
    slug: "textiles",
    icon: "🧵",
    productCount: 156,
  },
  {
    id: "cat-4",
    name: "Manufactura",
    slug: "manufactura",
    icon: "⚙️",
    productCount: 312,
  },
  {
    id: "cat-5",
    name: "Artesanias",
    slug: "artesanias",
    icon: "🏺",
    productCount: 98,
  },
  {
    id: "cat-6",
    name: "Automotriz",
    slug: "automotriz",
    icon: "🔧",
    productCount: 145,
  },
  {
    id: "cat-7",
    name: "Electrónicos",
    slug: "electronicos",
    icon: "💡",
    productCount: 89,
  },
  {
    id: "cat-8",
    name: "Materiales",
    slug: "materiales",
    icon: "🪨",
    productCount: 67,
  },
];

export const EXPORTER_PROFILE: ExporterProfile = {
  id: "exp-001",
  email: "carlos@agavepremium.mx",
  name: "Carlos Mendoza",
  role: "EXPORTER" as UserRole.EXPORTER,
  avatar:
    "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
  company: "Agave Premium Export S.A. de C.V.",
  phone: "+52 33 1234 5678",
  country: "MX",
  createdAt: "2024-03-15T00:00:00Z",
  rfc: "APE240315XX0",
  description:
    "Exportamos productos premium de agave, tequila artesanal y derivados hacia el mercado estadounidense. Certificaciones orgánicas y comercio justo.",
  categories: ["Alimentos y Bebidas", "Agricultura"],
  rating: 4.8,
  totalReviews: 156,
  totalProducts: 24,
  totalOrders: 489,
  verified: true,
  bannerImage:
    "https://images.unsplash.com/photo-1569930784237-ea65a2f40a83?w=1200&h=400&fit=crop",
  location: "Guadalajara, Jalisco",
};

export const CLIENT_PROFILE: ClientProfile = {
  id: "cli-001",
  email: "sarah@premiumfoods.us",
  name: "Sarah Thompson",
  role: "CLIENT" as UserRole.CLIENT,
  avatar:
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
  company: "Premium Foods Distribution LLC",
  phone: "+1 (512) 555-0147",
  country: "US",
  createdAt: "2024-06-20T00:00:00Z",
  shippingAddresses: [
    {
      id: "addr-1",
      label: "Warehouse",
      street: "4521 Industrial Blvd",
      city: "Houston",
      state: "TX",
      zip: "77001",
      country: "US",
      isDefault: true,
    },
    {
      id: "addr-2",
      label: "Office",
      street: "1200 Commerce St, Suite 400",
      city: "Dallas",
      state: "TX",
      zip: "75201",
      country: "US",
      isDefault: false,
    },
  ],
};

export const PRODUCTS: Product[] = [
  {
    id: "prod-001",
    exporterId: "exp-001",
    exporterName: "Agave Premium Export",
    name: "Tequila Reposado Artesanal",
    slug: "tequila-reposado-artesanal",
    description:
      "Tequila reposado 100% agave azul, añejado 8 meses en barricas de roble blanco americano. Notas de vainilla, caramelo y agave cocido. Producción limitada de lotes pequeños con agave cultivado en los Altos de Jalisco.",
    shortDescription: "Tequila reposado 100% agave azul, 8 meses en barrica",
    images: [
      "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=600&h=600&fit=crop",
    ],
    category: "Alimentos y Bebidas",
    subcategory: "Destilados",
    price: 42.5,
    currency: "USD",
    minOrder: 48,
    unit: "botellas",
    stock: 2400,
    origin: "Jalisco, México",
    certifications: ["NOM-006-SCFI", "USDA Organic", "CRT Certified"],
    tags: ["tequila", "premium", "orgánico", "artesanal"],
    rating: 4.9,
    totalReviews: 87,
    createdAt: "2024-08-01T00:00:00Z",
    featured: true,
  },
  {
    id: "prod-002",
    exporterId: "exp-001",
    exporterName: "Agave Premium Export",
    name: "Miel de Agave Orgánica",
    slug: "miel-de-agave-organica",
    description:
      "Miel de agave 100% natural, sin aditivos ni conservadores. Ideal como endulzante natural de bajo índice glucémico. Presentación en botella de vidrio de 750ml.",
    shortDescription: "Endulzante natural orgánico de agave azul",
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&h=600&fit=crop",
    ],
    category: "Alimentos y Bebidas",
    subcategory: "Endulzantes",
    price: 8.75,
    currency: "USD",
    minOrder: 120,
    unit: "botellas",
    stock: 5000,
    origin: "Jalisco, México",
    certifications: ["USDA Organic", "Non-GMO Project"],
    tags: ["agave", "orgánico", "endulzante", "natural"],
    rating: 4.7,
    totalReviews: 54,
    createdAt: "2024-09-15T00:00:00Z",
    featured: true,
  },
  {
    id: "prod-003",
    exporterId: "exp-002",
    exporterName: "Textiles Oaxaca",
    name: "Rebozo de Seda Artesanal",
    slug: "rebozo-seda-artesanal",
    description:
      "Rebozo tejido a mano en telar de cintura por artesanas zapotecas. Seda natural teñida con tintes naturales de cochinilla y añil. Cada pieza es única y tarda aproximadamente 3 meses en completarse.",
    shortDescription: "Rebozo de seda tejido a mano con tintes naturales",
    images: [
      "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&h=600&fit=crop",
    ],
    category: "Textiles",
    subcategory: "Artesanal",
    price: 185.0,
    currency: "USD",
    minOrder: 10,
    unit: "piezas",
    stock: 45,
    origin: "Oaxaca, México",
    certifications: ["Fair Trade", "Handmade"],
    tags: ["artesanal", "seda", "oaxaca", "tejido a mano"],
    rating: 5.0,
    totalReviews: 23,
    createdAt: "2024-07-20T00:00:00Z",
    featured: true,
  },
  {
    id: "prod-004",
    exporterId: "exp-003",
    exporterName: "Café Sierra Norte",
    name: "Café de Especialidad Chiapas",
    slug: "cafe-especialidad-chiapas",
    description:
      "Café de altura cultivado a 1,800 msnm en la Sierra Norte de Chiapas. Perfil de taza con notas de chocolate amargo, frutos rojos y cítricos. Proceso de lavado con fermentación controlada de 36 horas.",
    shortDescription:
      "Café de especialidad de altura, notas de chocolate y frutos rojos",
    images: [
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop",
    ],
    category: "Alimentos y Bebidas",
    subcategory: "Café",
    price: 14.5,
    currency: "USD",
    minOrder: 100,
    unit: "kg",
    stock: 8000,
    origin: "Chiapas, México",
    certifications: ["Fair Trade", "Rainforest Alliance", "USDA Organic"],
    tags: ["café", "especialidad", "orgánico", "chiapas"],
    rating: 4.8,
    totalReviews: 112,
    createdAt: "2024-06-10T00:00:00Z",
    featured: true,
  },
  {
    id: "prod-005",
    exporterId: "exp-004",
    exporterName: "Cerámica Talavera Puebla",
    name: "Vajilla Talavera Clásica 24 piezas",
    slug: "vajilla-talavera-clasica",
    description:
      "Set de vajilla de talavera poblana certificada. Incluye 8 platos base, 8 platos soperos y 8 platos de postre. Pintada a mano con diseños tradicionales en azul cobalto sobre blanco.",
    shortDescription: "Vajilla de talavera poblana pintada a mano, 24 piezas",
    images: [
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=600&fit=crop",
    ],
    category: "Artesanias",
    subcategory: "Cerámica",
    price: 320.0,
    currency: "USD",
    minOrder: 5,
    unit: "sets",
    stock: 30,
    origin: "Puebla, México",
    certifications: ["Denominación de Origen Talavera"],
    tags: ["talavera", "cerámica", "artesanal", "puebla"],
    rating: 4.9,
    totalReviews: 34,
    createdAt: "2024-10-01T00:00:00Z",
    featured: false,
  },
  {
    id: "prod-006",
    exporterId: "exp-005",
    exporterName: "Aguacates del Valle",
    name: "Aguacate Hass Premium",
    slug: "aguacate-hass-premium",
    description:
      "Aguacate Hass de exportación, calibre 48-60, cultivado en Michoacán. Selección premium con maduración controlada. Empaque en cajas de 10kg con atmósfera modificada para mayor vida de anaquel.",
    shortDescription: "Aguacate Hass de exportación, calibre premium",
    images: [
      "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&h=600&fit=crop",
    ],
    category: "Agricultura",
    subcategory: "Frutas",
    price: 32.0,
    currency: "USD",
    minOrder: 50,
    unit: "cajas (10kg)",
    stock: 500,
    origin: "Michoacán, México",
    certifications: ["USDA APHIS", "Global GAP", "Primus GFS"],
    tags: ["aguacate", "hass", "premium", "michoacán"],
    rating: 4.6,
    totalReviews: 198,
    createdAt: "2024-05-01T00:00:00Z",
    featured: true,
  },
  {
    id: "prod-007",
    exporterId: "exp-006",
    exporterName: "Auto Parts Monterrey",
    name: "Arnés Eléctrico Automotriz OEM",
    slug: "arnes-electrico-automotriz-oem",
    description:
      "Arnés eléctrico de cableado completo para aplicaciones automotrices. Compatible con especificaciones OEM de principales armadoras. Producción bajo norma IATF 16949.",
    shortDescription: "Arnés eléctrico OEM para industria automotriz",
    images: [
      "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=600&h=600&fit=crop",
    ],
    category: "Automotriz",
    subcategory: "Componentes",
    price: 125.0,
    currency: "USD",
    minOrder: 200,
    unit: "piezas",
    stock: 10000,
    origin: "Nuevo León, México",
    certifications: ["IATF 16949", "ISO 9001"],
    tags: ["automotriz", "arnés", "OEM", "cableado"],
    rating: 4.5,
    totalReviews: 67,
    createdAt: "2024-04-15T00:00:00Z",
    featured: false,
  },
  {
    id: "prod-008",
    exporterId: "exp-007",
    exporterName: "Mezcal Ancestral Oaxaca",
    name: "Mezcal Espadín Joven",
    slug: "mezcal-espadin-joven",
    description:
      "Mezcal joven de agave espadín, destilado en alambique de cobre. Producción artesanal en Santiago Matatlán, Oaxaca. Notas ahumadas con toques cítricos y herbales. 45% alc. vol.",
    shortDescription: "Mezcal artesanal de agave espadín, destilación en cobre",
    images: [
      "https://images.unsplash.com/photo-1568916799050-4a2b0b14e4c3?w=600&h=600&fit=crop",
    ],
    category: "Alimentos y Bebidas",
    subcategory: "Destilados",
    price: 38.0,
    currency: "USD",
    minOrder: 36,
    unit: "botellas",
    stock: 1200,
    origin: "Oaxaca, México",
    certifications: ["NOM-070-SCFI", "CRM Certified"],
    tags: ["mezcal", "artesanal", "oaxaca", "espadín"],
    rating: 4.7,
    totalReviews: 45,
    createdAt: "2024-11-01T00:00:00Z",
    featured: true,
  },
];

export const ORDERS: Order[] = [
  {
    id: "ord-001",
    orderNumber: "MXP-2025-00147",
    clientId: "cli-001",
    clientName: "Premium Foods Distribution LLC",
    exporterId: "exp-001",
    exporterName: "Agave Premium Export",
    items: [
      {
        productId: "prod-001",
        productName: "Tequila Reposado Artesanal",
        quantity: 96,
        unitPrice: 42.5,
        totalPrice: 4080,
      },
      {
        productId: "prod-002",
        productName: "Miel de Agave Orgánica",
        quantity: 240,
        unitPrice: 8.75,
        totalPrice: 2100,
      },
    ],
    subtotal: 6180,
    shippingCost: 450,
    tax: 0,
    total: 6630,
    currency: "USD",
    status: "SHIPPED" as OrderStatus.SHIPPED,
    shippingAddress: {
      id: "addr-1",
      label: "Warehouse",
      street: "4521 Industrial Blvd",
      city: "Houston",
      state: "TX",
      zip: "77001",
      country: "US",
      isDefault: true,
    },
    trackingNumber: "FDX-MX-2025-984712",
    estimatedDelivery: "2025-04-22T00:00:00Z",
    createdAt: "2025-04-10T14:30:00Z",
    updatedAt: "2025-04-15T09:00:00Z",
  },
  {
    id: "ord-002",
    orderNumber: "MXP-2025-00148",
    clientId: "cli-002",
    clientName: "Artisan Goods Co.",
    exporterId: "exp-001",
    exporterName: "Agave Premium Export",
    items: [
      {
        productId: "prod-001",
        productName: "Tequila Reposado Artesanal",
        quantity: 48,
        unitPrice: 42.5,
        totalPrice: 2040,
      },
    ],
    subtotal: 2040,
    shippingCost: 280,
    tax: 0,
    total: 2320,
    currency: "USD",
    status: "CONFIRMED" as OrderStatus.CONFIRMED,
    shippingAddress: {
      id: "addr-3",
      label: "Main",
      street: "890 Artisan Way",
      city: "Austin",
      state: "TX",
      zip: "73301",
      country: "US",
      isDefault: true,
    },
    createdAt: "2025-04-14T10:00:00Z",
    updatedAt: "2025-04-14T10:00:00Z",
  },
  {
    id: "ord-003",
    orderNumber: "MXP-2025-00149",
    clientId: "cli-001",
    clientName: "Premium Foods Distribution LLC",
    exporterId: "exp-003",
    exporterName: "Café Sierra Norte",
    items: [
      {
        productId: "prod-004",
        productName: "Café de Especialidad Chiapas",
        quantity: 500,
        unitPrice: 14.5,
        totalPrice: 7250,
      },
    ],
    subtotal: 7250,
    shippingCost: 620,
    tax: 0,
    total: 7870,
    currency: "USD",
    status: "DELIVERED" as OrderStatus.DELIVERED,
    shippingAddress: {
      id: "addr-1",
      label: "Warehouse",
      street: "4521 Industrial Blvd",
      city: "Houston",
      state: "TX",
      zip: "77001",
      country: "US",
      isDefault: true,
    },
    trackingNumber: "UPS-MX-2025-447821",
    estimatedDelivery: "2025-03-28T00:00:00Z",
    createdAt: "2025-03-20T08:45:00Z",
    updatedAt: "2025-03-28T16:20:00Z",
  },
  {
    id: "ord-004",
    orderNumber: "MXP-2025-00150",
    clientId: "cli-003",
    clientName: "Desert Spirits Inc.",
    exporterId: "exp-001",
    exporterName: "Agave Premium Export",
    items: [
      {
        productId: "prod-001",
        productName: "Tequila Reposado Artesanal",
        quantity: 192,
        unitPrice: 42.5,
        totalPrice: 8160,
      },
      {
        productId: "prod-002",
        productName: "Miel de Agave Orgánica",
        quantity: 480,
        unitPrice: 8.75,
        totalPrice: 4200,
      },
    ],
    subtotal: 12360,
    shippingCost: 890,
    tax: 0,
    total: 13250,
    currency: "USD",
    status: "PROCESSING" as OrderStatus.PROCESSING,
    shippingAddress: {
      id: "addr-4",
      label: "Distribution Center",
      street: "2200 E Camelback Rd",
      city: "Phoenix",
      state: "AZ",
      zip: "85016",
      country: "US",
      isDefault: true,
    },
    createdAt: "2025-04-16T11:20:00Z",
    updatedAt: "2025-04-16T11:20:00Z",
  },
  {
    id: "ord-005",
    orderNumber: "MXP-2025-00151",
    clientId: "cli-001",
    clientName: "Premium Foods Distribution LLC",
    exporterId: "exp-005",
    exporterName: "Aguacates del Valle",
    items: [
      {
        productId: "prod-006",
        productName: "Aguacate Hass Premium",
        quantity: 100,
        unitPrice: 32.0,
        totalPrice: 3200,
      },
    ],
    subtotal: 3200,
    shippingCost: 540,
    tax: 0,
    total: 3740,
    currency: "USD",
    status: "PENDING" as OrderStatus.PENDING,
    shippingAddress: {
      id: "addr-1",
      label: "Warehouse",
      street: "4521 Industrial Blvd",
      city: "Houston",
      state: "TX",
      zip: "77001",
      country: "US",
      isDefault: true,
    },
    createdAt: "2025-04-17T09:00:00Z",
    updatedAt: "2025-04-17T09:00:00Z",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-001",
    productId: "prod-001",
    clientId: "cli-001",
    clientName: "Sarah Thompson",
    clientAvatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&h=50&fit=crop&crop=face",
    rating: 5,
    comment:
      "Exceptional quality tequila. Our customers love it. The packaging arrived in perfect condition and the flavor profile is exactly as described. Will definitely reorder.",
    createdAt: "2025-03-20T00:00:00Z",
  },
  {
    id: "rev-002",
    productId: "prod-001",
    clientId: "cli-002",
    clientName: "James Parker",
    rating: 5,
    comment:
      "Best tequila we've sourced from Mexico. The artisanal production really shows in the taste. Great communication from the exporter throughout the process.",
    createdAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "rev-003",
    productId: "prod-004",
    clientId: "cli-001",
    clientName: "Sarah Thompson",
    clientAvatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&h=50&fit=crop&crop=face",
    rating: 4,
    comment:
      "Great specialty coffee. The chocolate notes are prominent and our roasters are very happy with the bean quality. Delivery took a bit longer than expected.",
    createdAt: "2025-03-30T00:00:00Z",
  },
  {
    id: "rev-004",
    productId: "prod-006",
    clientId: "cli-004",
    clientName: "Michael Chen",
    rating: 5,
    comment:
      "Premium avocados as advertised. Perfect ripeness on arrival thanks to the controlled atmosphere packaging. Consistent quality across all boxes.",
    createdAt: "2025-04-05T00:00:00Z",
  },
  {
    id: "rev-005",
    productId: "prod-003",
    clientId: "cli-005",
    clientName: "Lisa Anderson",
    rating: 5,
    comment:
      "Absolutely stunning rebozos. Each piece is a work of art. Our boutique customers are willing to pay premium prices for this level of craftsmanship.",
    createdAt: "2025-01-28T00:00:00Z",
  },
];

export const ANALYTICS_OVERVIEW: AnalyticsOverview = {
  totalRevenue: 147520,
  totalOrders: 489,
  totalProducts: 24,
  averageRating: 4.8,
  revenueChange: 12.5,
  ordersChange: 8.3,
  viewsTotal: 15420,
  viewsChange: 22.1,
};

export const REVENUE_TREND: RevenueDataPoint[] = [
  { month: "Oct", revenue: 9800 },
  { month: "Nov", revenue: 12400 },
  { month: "Dic", revenue: 15200 },
  { month: "Ene", revenue: 11800 },
  { month: "Feb", revenue: 13600 },
  { month: "Mar", revenue: 16900 },
  { month: "Abr", revenue: 14200 },
];

export const TOP_PRODUCTS: TopProduct[] = [
  {
    productId: "prod-001",
    productName: "Tequila Reposado Artesanal",
    totalSold: 1248,
    revenue: 53040,
  },
  {
    productId: "prod-002",
    productName: "Miel de Agave Orgánica",
    totalSold: 3600,
    revenue: 31500,
  },
  {
    productId: "prod-004",
    productName: "Café de Especialidad Chiapas",
    totalSold: 2100,
    revenue: 30450,
  },
  {
    productId: "prod-006",
    productName: "Aguacate Hass Premium",
    totalSold: 850,
    revenue: 27200,
  },
  {
    productId: "prod-008",
    productName: "Mezcal Espadín Joven",
    totalSold: 432,
    revenue: 16416,
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "notif-001",
    userId: "exp-001",
    title: "Nuevo pedido recibido",
    message: "Desert Spirits Inc. ha realizado un pedido por $13,250 USD",
    type: "order",
    read: false,
    createdAt: "2025-04-16T11:20:00Z",
  },
  {
    id: "notif-002",
    userId: "exp-001",
    title: "Pago confirmado",
    message: "El pago del pedido MXP-2025-00147 ha sido confirmado",
    type: "payment",
    read: false,
    createdAt: "2025-04-15T14:00:00Z",
  },
  {
    id: "notif-003",
    userId: "exp-001",
    title: "Nueva reseña",
    message:
      "Sarah Thompson dejó una reseña de 5 estrellas en Tequila Reposado",
    type: "review",
    read: true,
    createdAt: "2025-04-14T09:30:00Z",
  },
  {
    id: "notif-004",
    userId: "exp-001",
    title: "Envío entregado",
    message: "El pedido MXP-2025-00149 fue entregado exitosamente",
    type: "shipping",
    read: true,
    createdAt: "2025-03-28T16:20:00Z",
  },
];

export const SHIPMENTS: LogisticsShipment[] = [
  {
    id: "ship-001",
    orderId: "ord-001",
    carrier: "FedEx International",
    trackingNumber: "FDX-MX-2025-984712",
    origin: "Guadalajara, JAL, MX",
    destination: "Houston, TX, US",
    status: "in_transit",
    estimatedDelivery: "2025-04-22T00:00:00Z",
    events: [
      {
        date: "2025-04-15T09:00:00Z",
        location: "Guadalajara, JAL",
        description: "Paquete recogido en origen",
      },
      {
        date: "2025-04-15T18:00:00Z",
        location: "Guadalajara, JAL",
        description: "En tránsito a centro de distribución",
      },
      {
        date: "2025-04-16T06:00:00Z",
        location: "Monterrey, NL",
        description: "En centro de distribución",
      },
      {
        date: "2025-04-16T14:00:00Z",
        location: "Laredo, TX",
        description: "En proceso de aduana",
      },
    ],
  },
];
